version: 0.2
# env:
#   secrets-manager:
#     LOGIN: outside-fe:SONAR_TOKEN
#     # HOST: outside-fe:HOST
#     # Organization: outside-fe:Organization
#     # Project: outside-fe:Project
phases:
  install:
    commands:
      - echo "Install phase ..."
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - apt-get update
      - apt-get install --yes openjdk-11-jre
      - java -version
      # - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      # - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      # - rm -rf sonar-scanner-cli-5.0.1.3006-linux.zip
      # - export PATH=$PATH:./sonar-scanner-5.0.1.3006-linux/bin/
      - npm install --legacy-peer-deps
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - echo "sonar.java.binaries=**/*.java" > sonar.properties
      - echo "sonar.java.binaries=**/target/classes" > sonar.properties
      - export SONAR_SCANNER_OPTS="-server"
  build:
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm run build:dev
      - sonar-scanner -X -Dsonar.login=04f8c0ee1199dc2dd8ea60439726a36eeacc24a3 -Dsonar.organization=test-dev9292 -Dsonar.projectKey=test-dev9292_ashish -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
artifacts:
  name: "BuildOutput"
  files:
    - '**/*'
  base-directory: 'dist/outside-fe'

  # version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#   pre_build:
#     commands:
#       - echo "Prebuild, installing npm dependencies"
#       - npm install --legacy-peer-deps 
#   build:
#     commands:
#       - echo "Starting the build step"
#       - export NODE_OPTIONS=--openssl-legacy-provider
#       - npm run build:dev
#       - echo "Finished"
# artifacts:
#   name: "BuildOutput"
#   files:
#     - '**/*'
#   base-directory: 'dist/outside-fe'
