version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "Prebuild, installing npm dependencies"
      - npm install --legacy-peer-deps 
  build:
    commands:
      - echo "Starting the build step"
      - npm run build:dev
      - echo "Finished"
artifacts:
  name: "BuildOutput"
  files:
    - '**/*'
  base-directory: 'dist/outside-fe'

# For Amplify buildspec File 
# version: 1
# frontend:
#   phases:
#     preBuild:
#       commands:
#         - npm install --legacy-peer-deps
#     build:
#       commands:
#         - node -v
#         - npm run build:dev
#   artifacts:
#     baseDirectory: 'dist/outside-fe'
#     files:
#       - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*