version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run: npm install --legacy-peer-deps && npm run build:production
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Load Environment Variables & Deploy to S3
          command: |
              source .env
              sudo aws s3 sync ./dist/outside-fe s3://outside-fe-circle-ci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build


