version: 2.1
executors:
  angular_executor:
    docker:
      - image: circleci/node:12.14.0-browsers

jobs:
  build:
    executor: angular_executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-dep

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: npm run build:production

      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id "AKIASHRYCLQM5SBLHGGB"
            aws configure set aws_secret_access_key "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"
            aws configure set default.region "us-east-1"
            aws s3 sync ./dist/outside-fe s3://outside-fe-circle-ci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build




# phases:
#   install:
#     runtime-versions:
#       nodejs: 16
#   pre_build:
#     commands:
#       - echo "Prebuild, installing npm dependencies"
#       - npm install --legacy-peer-deps 
#   build:
#     commands:
#       - echo "Starting the build step"
#       - npm run build:$stage
#       - echo "Finished"
# artifacts:
#   name: "BuildOutput"
#   files:
#     - '**/*'
#   base-directory: 'dist/outside-fe'
